INSERT INTO product (name, supplier, price) VALUES ('Laptop ThinkPad', 'Lenovo', 1000.00);
INSERT INTO product (name, supplier, price) VALUES ('MacBook Pro', 'Apple', 1200.00);
INSERT INTO product (name, supplier, price) VALUES ('Gaming Monitor', 'Asus', 250.00);
INSERT INTO product (name, supplier, price) VALUES ('Wireless Mouse', 'Logitech', 25.00);
INSERT INTO product (name, supplier, price) VALUES ('Gaming Keyboard', 'Corsair', 100.00);
INSERT INTO product (name, supplier, price) VALUES ('SSD 1TB', 'Samsung', 150.00);
INSERT INTO product (name, supplier, price) VALUES ('Graphic Card RTX 3080', 'NVIDIA', 700.00);
INSERT INTO product (name, supplier, price) VALUES ('RAM 32GB', 'Crucial', 120.00);
INSERT INTO product (name, supplier, price) VALUES ('USB-C Hub', 'Anker', 40.00);
INSERT INTO product (name, supplier, price) VALUES ('External HDD 2TB', 'Seagate', 80.00);
INSERT INTO user (username, password) VALUES ('usuario1', '$2y$10$ro8.ujuzZEbYIQCc5j4z8eWiZrpJThXNPGZSwmh9Ey1S6WaX6ZcMa');